feat: function to clear existing video cache
OutdatedGuy/cached_video_player_plus pull request #14
Opened 2024-03-21 16:38 UTC by chorauoc

- Added removeFileFromCache function to clear cache and get storage entry
- Exposed getter for isDisposed to check if player already disposed
- Added clearCache function to clear all cache and get storage
- Added addListener override method to prevent exception to be thrown when attempting to add a listener after the controller has already been disposed
- Code refactor

2024-03-23 17:01 UTC, OutdatedGuy commented
Thanks for the contribution! I'll review the code when I get some free time.

2024-03-25 14:18 UTC, OutdatedGuy requested changes
Looks like a lot of formatting are changed.

Can you first run `dart fix --apply` and then `dart format .`

2024-03-25 16:06 UTC, chorauoc commented
Formatted as requested

2024-03-26 11:24 UTC, OutdatedGuy requested changes
Thanks for the contribution. There are some changes I have requested. Please resolve them and we can merge this PR.

2024-03-26 11:24 UTC, OutdatedGuy commented on lib/cached_video_player_plus.dart
> +  final bool skipCache;
Please add a more descriptive comment for this so users may know what this actually does.

2024-03-26 11:24 UTC, OutdatedGuy commented on lib/cached_video_player_plus.dart
> +    if (skipCache) return false;
Can we add this where `_isCachingSupported` is used instead? So that this getter only returns what it should.

2024-03-26 11:24 UTC, OutdatedGuy commented on lib/cached_video_player_plus.dart
> +  final CacheManager _cacheManager = DefaultCacheManager();
Just add a new line above this, so that there is separation between _video_player_ variables and our variables.

2024-03-26 11:24 UTC, OutdatedGuy commented on lib/cached_video_player_plus.dart
> +  bool get isDisposed => _isDisposed;
Why is this necessary? I don't see it used anywhere? Is it for public usage?

2024-03-26 11:24 UTC, OutdatedGuy commented on lib/cached_video_player_plus.dart
> +  }
This shouldn't exist as it can wipe data aside from `cached_video_player_plus` data.

2024-03-26 11:24 UTC, OutdatedGuy commented on lib/cached_video_player_plus.dart
> +
This is off-topic from the pull request. If necessary it can be implemented in another PR.

Please revert this.

2024-03-26 11:24 UTC, OutdatedGuy commented on lib/cached_video_player_plus.dart
> +        }));
Please add a comma `,` before the last closing parentheses `)`.

2024-03-26 11:24 UTC, OutdatedGuy commented on lib/cached_video_player_plus.dart
> +      )}');
Please add a comma `,` before the last closing parentheses `)`.

2024-03-26 11:24 UTC, OutdatedGuy commented on lib/cached_video_player_plus.dart
> +  }
A controller class method should only act on it own data. So we can have two functions here instead, one static and one class method.

The static method (suppose named `removeCacheFor`) should have the `key` parameter mandatorily and remove the cache for they `key` only.

The class method (suppose named `removeCachedFile`) should not take any arguments and remove the cache for `dataSource` only.

Also the `removeCachedFile` should only execute if the controller is initialized using `.network` or `.networkUrl`.

2024-04-10 23:15 UTC, OutdatedGuy commented
Hi @chorauoc, are you still working on this PR?

2024-05-23 02:54 UTC, OutdatedGuy approved these changes
LGTM!

2024-05-23 02:56 UTC, merged