Added custom cacheManager and cache key
OutdatedGuy/cached_video_player_plus pull request #48
Opened 2024-09-27 13:23 UTC by rignaneseleo

**Summary**

This PR addresses issue #47 by introducing the ability to pass a custom `cacheManager` and `cacheKey` as parameters. This makes the library more flexible and customizable, similar to how `CachedNetworkImage` handles caching.

**Key Changes**

- Added support for passing `cacheManager` and `cacheKey` parameters.
- This allows developers to:
  - Use custom cache managers tailored to their specific needs.
  - Preload videos from different sources using the same `cacheManager` and `cacheKey` for efficient caching.
  
- Removed the `_storage` variable, as it was redundant. The `cacheManager` already tracks cache expiry dates and manages cached items, making additional storage management unnecessary.

**Advantages**

- Preload videos from anywhere
- Greater flexibility in cache management.
- Streamlined and simplified code by removing redundant storage handling.
- Easier integration with preloaded media files.

Thank you for reviewing!

2024-10-23 13:22 UTC, OutdatedGuy commented
@rignaneseleo thanks for the contribution. I'll review it once I get some free time.

2024-11-08 06:03 UTC, OutdatedGuy requested changes
Hi @rignaneseleo, thanks for the PR. I can see the advantages of this PR however there are some changes I don't understand.

Why is the `get_storage` mechanism removed? It is implemented so that users can pass dynamic cache invalidation values while retrieving the video file.

Can you explain on that?

2024-12-05 10:14 UTC, Musaddiq625 commented
Hello @rignaneseleo 
Ive a little concern on this idea
I mean this is the whole concept of this package to cache the video

but if we allow developers to add their own custom cache feature
dont you think we are **bypassing the package implementation**?

2025-03-16 23:48 UTC, gmr-renato commented
@rignaneseleo Would it be better to pass just the cache key as an argument? Changing the whole instance of the cache seems too much for me. I'm reproducing your PR locally on my project by the way.

2025-07-08 16:29 UTC, closed without merging

2025-07-08 16:30 UTC, OutdatedGuy commented
Closing as stale